/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CompaniesCreateCompanyRequestCompany } from './companies-create-company-request-company';
import { CompaniesCreateCompanyRequestUser } from './companies-create-company-request-user';

/**
 * 
 * @export
 * @interface CompaniesCreateCompanyRequest
 */
export interface CompaniesCreateCompanyRequest {
    /**
     * 
     * @type {CompaniesCreateCompanyRequestUser}
     * @memberof CompaniesCreateCompanyRequest
     */
    'user': CompaniesCreateCompanyRequestUser;
    /**
     * 
     * @type {CompaniesCreateCompanyRequestCompany}
     * @memberof CompaniesCreateCompanyRequest
     */
    'company': CompaniesCreateCompanyRequestCompany;
}

