/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CompaniesCreateCompanyRequestCompanyAddressesInner } from './companies-create-company-request-company-addresses-inner';

/**
 * 
 * @export
 * @interface CompaniesCreateCompanyRequestCompany
 */
export interface CompaniesCreateCompanyRequestCompany {
    /**
     * The legal name of the company.
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompany
     */
    'name': string;
    /**
     * The name of the company.
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompany
     */
    'trade_name'?: string;
    /**
     * The employer identification number (EIN) of the company.
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompany
     */
    'ein'?: string;
    /**
     * The states in which the company operates. States should be included by their two letter code, i.e. NY for New York. 
     * @type {Array<string>}
     * @memberof CompaniesCreateCompanyRequestCompany
     */
    'states'?: Array<string>;
    /**
     * The number of employees in the company.
     * @type {number}
     * @memberof CompaniesCreateCompanyRequestCompany
     */
    'number_employees'?: number;
    /**
     * The locations for the company. This includes mailing, work, and filing addresses.
     * @type {Array<CompaniesCreateCompanyRequestCompanyAddressesInner>}
     * @memberof CompaniesCreateCompanyRequestCompany
     */
    'addresses'?: Array<CompaniesCreateCompanyRequestCompanyAddressesInner>;
}

