/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CompanyBenefitsRemoveBenefitResponseErrorsBaseInner } from './company-benefits-remove-benefit-response-errors-base-inner';

/**
 * 
 * @export
 * @interface CompanyBenefitsRemoveBenefitResponseErrors
 */
export interface CompanyBenefitsRemoveBenefitResponseErrors {
    /**
     * 
     * @type {Array<CompanyBenefitsRemoveBenefitResponseErrorsBaseInner>}
     * @memberof CompanyBenefitsRemoveBenefitResponseErrors
     */
    'base'?: Array<CompanyBenefitsRemoveBenefitResponseErrorsBaseInner>;
}

