/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompaniesCreateCompanyRequestCompanyAddressesInner
 */
export interface CompaniesCreateCompanyRequestCompanyAddressesInner {
    /**
     * 
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'street_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'street_2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'phone'?: string;
    /**
     * Whether or not this is a primary address for the company. If set to true, the address will be used as the mailing and filing address for the company and will be added as a work location. If set to false or not included, the address will only be added as a work location for the company. If multiple addresses are included, only one should be marked as primary.
     * @type {string}
     * @memberof CompaniesCreateCompanyRequestCompanyAddressesInner
     */
    'is_primary'?: string;
}

