/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContractorBody } from './contractor-body';

/**
 * 
 * @export
 * @interface ContractorsCreateIndividualOrBusinessRequest
 */
export interface ContractorsCreateIndividualOrBusinessRequest {
    /**
     * The contractor type.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'type': ContractorsCreateIndividualOrBusinessRequestTypeEnum;
    /**
     * The contractor’s wage type. 
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'wage_type': ContractorsCreateIndividualOrBusinessRequestWageTypeEnum;
    /**
     * The day when the contractor will start working for the company. 
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'start_date': string;
    /**
     * The contractor’s hourly rate. This attribute is required if the wage_type is `Hourly`.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'hourly_rate'?: string;
    /**
     * Whether the contractor or the payroll admin will complete onboarding in Gusto. Self-onboarding is recommended so that contractors receive Gusto accounts. If self_onboarding is true, then email is required.
     * @type {boolean}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'self_onboarding'?: boolean;
    /**
     * The contractor’s email address.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'email'?: string;
    /**
     * The contractor’s first name. This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'first_name'?: string;
    /**
     * The contractor’s last name. This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'last_name'?: string;
    /**
     * The contractor’s middle initial. This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'middle_initial'?: string;
    /**
     * The boolean flag indicating whether Gusto will file a new hire report for the contractor. This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
     * @type {boolean}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'file_new_hire_report'?: boolean;
    /**
     * State where the contractor will be conducting the majority of their work for the company. This value is used when generating the new hire report. This attribute is required for `Individual` contractors if `file_new_hire_report` is true and will be ignored for `Business` contractors.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'work_state'?: string | null;
    /**
     * This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors. Social security number is needed to file the annual 1099 tax form.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'ssn'?: string;
    /**
     * The name of the contractor business. This attribute is required for `Business` contractors and will be ignored for `Individual` contractors.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'business_name'?: string;
    /**
     * The employer identification number of the contractor business. This attribute is optional for `Business` contractors and will be ignored for `Individual` contractors.
     * @type {string}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'ein'?: string;
    /**
     * The status of the contractor.
     * @type {boolean}
     * @memberof ContractorsCreateIndividualOrBusinessRequest
     */
    'is_active'?: boolean;
}

type ContractorsCreateIndividualOrBusinessRequestTypeEnum = 'Individual' | 'Business'
type ContractorsCreateIndividualOrBusinessRequestWageTypeEnum = 'Fixed' | 'Hourly'


