/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeBenefitsUpdateBenefitRequestContribution } from './employee-benefits-update-benefit-request-contribution';

/**
 * 
 * @export
 * @interface EmployeeBenefitsUpdateBenefitRequest
 */
export interface EmployeeBenefitsUpdateBenefitRequest {
    /**
     * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'version': string;
    /**
     * Whether the employee benefit is active.
     * @type {boolean}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'active'?: boolean;
    /**
     * The amount to be deducted, per pay period, from the employee\'s pay.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'employee_deduction'?: string;
    /**
     * Whether the employee deduction amount should be treated as a percentage to be deducted from each payroll.
     * @type {boolean}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'deduct_as_percentage'?: boolean;
    /**
     * The maximum employee deduction amount per year. A null value signifies no limit.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'employee_deduction_annual_maximum'?: string | null;
    /**
     * 
     * @type {EmployeeBenefitsUpdateBenefitRequestContribution}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'contribution'?: EmployeeBenefitsUpdateBenefitRequestContribution;
    /**
     * Whether the company contribution is elective (aka \"matching\"). For `tiered`, `elective_amount`, and `elective_percentage` contribution types this is ignored and assumed to be `true`.
     * @type {boolean}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'elective'?: boolean;
    /**
     * The maximum company contribution amount per year. A null value signifies no limit.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'company_contribution_annual_maximum'?: string | null;
    /**
     * Some benefits require additional information to determine their limit. For example, for an HSA benefit, the limit option should be either \"Family\" or \"Individual\". For a Dependent Care FSA benefit, the limit option should be either \"Joint Filing or Single\" or \"Married and Filing Separately\".
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'limit_option'?: string | null;
    /**
     * Whether the employee should use a benefit’s \"catch up\" rate. Only Roth 401k and 401k benefits use this value for employees over 50.
     * @type {boolean}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'catch_up'?: boolean;
    /**
     * The amount that the employee is insured for. Note: company contribution cannot be present if coverage amount is set.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'coverage_amount'?: string | null;
    /**
     * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life benefits. Note: when the value is not \"unset\", coverage amount and coverage salary multiplier are ignored.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'deduction_reduces_taxable_income'?: EmployeeBenefitsUpdateBenefitRequestDeductionReducesTaxableIncomeEnum;
    /**
     * The coverage amount as a multiple of the employee’s salary. Only applicable for Group Term Life benefits. Note: cannot be set if coverage amount is also set.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     */
    'coverage_salary_multiplier'?: string;
    /**
     * The amount to be paid, per pay period, by the company.
     * @type {string}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     * @deprecated
     */
    'company_contribution'?: string;
    /**
     * Whether the company contribution amount should be treated as a percentage to be deducted from each payroll.
     * @type {boolean}
     * @memberof EmployeeBenefitsUpdateBenefitRequest
     * @deprecated
     */
    'contribute_as_percentage'?: boolean;
}

type EmployeeBenefitsUpdateBenefitRequestDeductionReducesTaxableIncomeEnum = 'unset' | 'reduces_taxable_income' | 'does_not_reduce_taxable_income' | 'null'


