/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IntrospectionAccessTokenInfoResponseResource } from './introspection-access-token-info-response-resource';

/**
 * 
 * @export
 * @interface IntrospectionAccessTokenInfoResponse
 */
export interface IntrospectionAccessTokenInfoResponse {
    /**
     * Space delimited string of accessible scopes.
     * @type {string}
     * @memberof IntrospectionAccessTokenInfoResponse
     */
    'scope'?: string;
    /**
     * 
     * @type {IntrospectionAccessTokenInfoResponseResource}
     * @memberof IntrospectionAccessTokenInfoResponse
     */
    'resource'?: IntrospectionAccessTokenInfoResponseResource;
}

