/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the token resource.
 * @export
 * @interface IntrospectionAccessTokenInfoResponseResource
 */
export interface IntrospectionAccessTokenInfoResponseResource {
    /**
     * Type of object
     * @type {string}
     * @memberof IntrospectionAccessTokenInfoResponseResource
     */
    'type'?: string;
    /**
     * UUID of object
     * @type {string}
     * @memberof IntrospectionAccessTokenInfoResponseResource
     */
    'uuid'?: string;
}

