/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An array of hourly compensations for the employee. Hourly compensations include regular, overtime, and double overtime hours.
 * @export
 * @interface PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner
 */
export interface PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner {
    /**
     * The name of the compensation. This also serves as the unique, immutable identifier for this compensation.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner
     */
    'name'?: string;
    /**
     * The number of hours to be compensated for this pay period.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner
     */
    'hours'?: string;
    /**
     * The UUIDs of the job for the compensation.
     * @type {number}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner
     */
    'job_uuid'?: number;
}

