/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An array of fixed compensations for the employee. Fixed compensations include tips, bonuses, and one time reimbursements.
 * @export
 * @interface PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner
 */
export interface PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner {
    /**
     * The name of the compensation. This also serves as the unique, immutable identifier for this compensation.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner
     */
    'name'?: string;
    /**
     * The amount of the compensation for the pay period.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner
     */
    'amount'?: string;
    /**
     * The UUID of the job for the compensation.
     * @type {number}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner
     */
    'job_uuid'?: number;
}

