/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner } from './payrolls-update-by-id-request-employee-compensations-inner-fixed-compensations-inner';
import { PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner } from './payrolls-update-by-id-request-employee-compensations-inner-hourly-compensations-inner';
import { PayrollsUpdateByIdRequestEmployeeCompensationsInnerPaidTimeOffInner } from './payrolls-update-by-id-request-employee-compensations-inner-paid-time-off-inner';

/**
 * 
 * @export
 * @interface PayrollsUpdateByIdRequestEmployeeCompensationsInner
 */
export interface PayrollsUpdateByIdRequestEmployeeCompensationsInner {
    /**
     * The current version of this employee compensation from the prepared payroll. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'version'?: string;
    /**
     * The UUID of the employee.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'employee_uuid'?: string;
    /**
     * This employee will be excluded from payroll calculation and will not be paid for the payroll.
     * @type {boolean}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'excluded'?: boolean;
    /**
     * The employee\'s compensation payment method. Invalid values will be ignored.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'payment_method'?: PayrollsUpdateByIdRequestEmployeeCompensationsInnerPaymentMethodEnum;
    /**
     * Custom text that will be printed as a personal note to the employee on a paystub.
     * @type {string}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'memo'?: string;
    /**
     * 
     * @type {Array<PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner>}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'fixed_compensations'?: Array<PayrollsUpdateByIdRequestEmployeeCompensationsInnerFixedCompensationsInner>;
    /**
     * 
     * @type {Array<PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner>}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'hourly_compensations'?: Array<PayrollsUpdateByIdRequestEmployeeCompensationsInnerHourlyCompensationsInner>;
    /**
     * An array of all paid time off the employee is eligible for this pay period. Each paid time off object can be the name or the specific policy_uuid.
     * @type {Array<PayrollsUpdateByIdRequestEmployeeCompensationsInnerPaidTimeOffInner>}
     * @memberof PayrollsUpdateByIdRequestEmployeeCompensationsInner
     */
    'paid_time_off'?: Array<PayrollsUpdateByIdRequestEmployeeCompensationsInnerPaidTimeOffInner>;
}

type PayrollsUpdateByIdRequestEmployeeCompensationsInnerPaymentMethodEnum = 'Direct Deposit' | 'Check'


